name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        working-directory: [
          packages/state_machine_bloc,
          examples/flutter_timer_state_machine,
          examples/infinite_list_state_machine
        ]

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run tests
        run: flutter test